import { chromium } from "playwright";
const OUT = "/tmp/claude-0/-home-user-Voxx-/ac779d14-066e-5187-987d-76d086f6868c/scratchpad";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-gl=swiftshader","--enable-unsafe-swiftshader"] });
const ctx = await b.newContext({ viewport: { width: 1440, height: 950 } });
const p = await ctx.newPage();
const errs=[]; p.on("pageerror",e=>errs.push("PAGEERR "+e.message.slice(0,150)));
p.on("console",m=>{if(m.type()==="error")errs.push("CONSOLE "+m.text().slice(0,150));});
await p.goto("http://localhost:3000/login",{waitUntil:"domcontentloaded"});
await p.fill('input[type="email"]',process.env.VOX_EMAIL);
await p.fill('input[type="password"]',process.env.VOX_PASSWORD);
await Promise.all([p.waitForURL(u=>!u.pathname.includes("login"),{timeout:30000}).catch(()=>{}),p.click('button[type="submit"]')]);
await p.waitForTimeout(4000);
const target = process.env.TARGET || "http://localhost:3000/lab/suits";
await p.goto(target,{waitUntil:"domcontentloaded",timeout:120000});
await p.waitForTimeout(Number(process.env.WAIT||14000));
await p.screenshot({path:`${OUT}/${process.env.NAME||"suitbay"}.png`});
console.log("shot", target);
if(errs.length) console.log("ERRORS:\n"+[...new Set(errs)].slice(0,6).join("\n"));
await b.close();
