/**
 * Deciding whether a chat message is something to SAY or something to DO.
 *
 * Chat was the entry point that could not reach the orchestrator, so a user
 * could ask VOX to make three variations and get a paragraph about making three
 * variations. This closes that, at the smallest integration point: one decision
 * before the model call, and a branch.
 *
 * COST IS THE DESIGN CONSTRAINT. Classifying "how are you?" must not cost a
 * model call, or every conversational turn pays for the privilege of being
 * recognised as conversational. So the decision is made by the EXISTING
 * deterministic router pass and nothing else — `routeRequest` without a
 * classifier returns an empty plan whenever the deterministic pass has no
 * confident opinion, and an empty plan is exactly "just answer".
 *
 * That gives the honest reading in both directions: the router only claims a
 * request is executable when it can name which capabilities it needs and why.
 * Anything it cannot, stays conversation.
 *
 * The reply for an executed request is composed HERE, deterministically, from
 * what the run actually did — not generated by a second model call. Two
 * reasons, and the second matters more than the cost: a model writing prose
 * about a run it cannot see will describe the run it expects, and the whole
 * point of this layer is that VOX reports what happened.
 */

import { routeRequest } from "@/lib/capabilities/router";
import { getCapabilityAvailability } from "@/lib/capabilities/availability";
import type { CapabilityPlan } from "@/lib/capabilities/types";
import type { RequestProgress } from "@/lib/capabilities/trace";

export type ChatAction =
  /** Answer it. The ordinary path, and the common one. */
  | { kind: "conversational" }
  /** Run it. `plan` is the routed plan the orchestrator will expand. */
  | { kind: "executable"; plan: CapabilityPlan };

/**
 * Decides what to do with a message. Zero model calls.
 *
 * `hasVisualReference` is threaded through because the router uses it to
 * decide between generating and editing, and a chat turn with an attached
 * image is a genuinely different request from the same words without one.
 */
export async function decideChatAction(
  message: string,
  options: { hasVisualReference?: boolean } = {},
): Promise<ChatAction> {
  const trimmed = message.trim();
  if (!trimmed) return { kind: "conversational" };

  // No classifier argument, deliberately: the deterministic pass either has a
  // confident opinion or it does not, and "not sure" resolves to conversation
  // rather than to a paid guess.
  const plan = await routeRequest({
    request: trimmed,
    hasVisualReference: options.hasVisualReference,
    available: getCapabilityAvailability(),
  });

  if (plan.steps.length === 0) return { kind: "conversational" };
  return { kind: "executable", plan };
}

/** Reads a capability name the way a person would say it. */
const CAPABILITY_VERB: Record<string, string> = {
  MEMORY: "recall what I already know",
  RESEARCH: "research it",
  IMAGE_GENERATION: "generate the image",
  IMAGE_EDIT: "edit the image",
  VIDEO_GENERATION: "produce the video",
  MODEL_3D: "produce the 3D asset",
  VISUAL_QA: "review the result",
  EXECUTION: "change the application",
};

/** The one-line account of a plan, before it has run. */
export function describePlan(plan: CapabilityPlan): string {
  const parts = plan.steps.map((step) => CAPABILITY_VERB[step.capability] ?? step.capability.toLowerCase());
  if (parts.length === 0) return "";
  const list = parts.length === 1 ? parts[0] : `${parts.slice(0, -1).join(", ")}, then ${parts[parts.length - 1]}`;
  return `Working on it — I'll ${list}.`;
}

/**
 * Composes the reply from what the run actually did.
 *
 * Every clause below is read off the trace. Nothing here can report a success
 * the run did not have, because there is no sentence available that is not
 * derived from a persisted status.
 */
export function describeRunOutcome(trace: RequestProgress): string {
  const lines: string[] = [];

  const done = trace.steps.filter((s) => s.status === "COMPLETED").length;
  const failed = trace.steps.find((s) => s.status === "FAILED");
  const loop = trace.iterations[0];

  // A loop that ran out of attempts or hit a provider failure RETURNS rather
  // than throwing, so its step completes and the run reads as COMPLETED. Led
  // by step status alone this would open with "Done" and then contradict
  // itself two lines later. The loop's own verdict is the honest headline.
  const loopFailed =
    loop?.stoppedBecause != null && loop.stoppedBecause !== "APPROVE";
  if (trace.status === "COMPLETED" && loopFailed) {
    const nothingApproved = trace.artifacts.every((a) => a.state !== "ACTIVE" && a.state !== "APPROVED");
    switch (loop!.stoppedBecause) {
      case "STOP_EXECUTION_FAILURE":
        lines.push("That didn't work — the generator failed partway through.");
        break;
      case "STOP_PROVIDER_UNAVAILABLE":
        lines.push("I couldn't finish that: the provider or reviewer it needs isn't available.");
        break;
      case "STOP_NOT_FIXABLE_BY_GENERATION":
        lines.push("I stopped rather than keep generating — the problem isn't one another attempt can fix.");
        break;
      case "STOP_NO_MEANINGFUL_IMPROVEMENT":
        lines.push("I stopped early: the attempts had stopped getting meaningfully better.");
        break;
      default:
        lines.push("I ran out of attempts before it cleared the bar.");
    }
    if (nothingApproved && trace.artifacts.length === 0) {
      lines.push("Nothing usable was produced.");
    }
  } else {
    switch (trace.status) {
      case "WAITING_FOR_PERMISSION": {
        const awaiting = trace.awaiting;
        // Plain text, no markdown: the chat bubble renders text literally, so
        // asterisks and backticks would appear as asterisks and backticks.
        lines.push(
          awaiting
            ? `I've stopped and need your approval before going further — "${awaiting.description}" needs ${awaiting.requiredLevel} on ${awaiting.capability}.`
            : "I've stopped and need a permission granted before going further.",
        );
        lines.push(`${done} of ${trace.steps.length} steps are done. Grant it in Permissions and I'll continue from there.`);
        break;
      }
      case "FAILED":
        // The step's own error, not a paraphrase of it.
        lines.push(`That didn't work. ${failed ? `It failed at "${failed.description}": ${failed.error}` : "The run failed."}`);
        if (done > 0) lines.push(`${done} step(s) completed first, and everything they produced has been kept.`);
        break;
      case "CANCELLED":
        lines.push(`Stopped. ${done} of ${trace.steps.length} steps had completed, and their results are kept.`);
        break;
      case "COMPLETED":
        lines.push(`Done — ${done} step(s).`);
        break;
      default:
        lines.push(`Started, ${done} of ${trace.steps.length} steps complete so far.`);
    }
  }

  // What the iteration loop actually did, when there was one. This is the
  // sentence a user most wants and would otherwise have to open the workspace
  // to find.
  if (loop && loop.attempts.length > 0) {
    const passed = loop.attempts.find((a) => a.status === "PASS");
    const scores = loop.attempts.map((a) => (a.score == null ? "—" : String(a.score))).join(" → ");
    lines.push(
      passed
        ? `It took ${loop.attempts.length} attempt(s) to clear the bar (${scores}).`
        : `${loop.attempts.length} of ${loop.limit} attempts, and none passed review (${scores}). I kept the strongest.`,
    );
  }

  const approved = trace.artifacts.filter((a) => a.state === "ACTIVE" || a.state === "APPROVED");
  if (approved.length > 0) {
    const best = approved[0];
    lines.push(`Approved version ${best.version}${best.score != null ? ` (${best.score}/100)` : ""}.`);
  }

  // A DEGRADED plan is the most dangerous thing to leave unsaid. The router
  // drops stages whose provider is not configured, so a request for an image
  // can legitimately run to completion having generated nothing — and "Done —
  // 1 step" to someone who asked for a picture is technically true and
  // completely misleading. The notes name the missing configuration.
  if (trace.plan?.degraded) {
    lines.push(
      trace.plan.notes.length > 0
        ? `I couldn't do all of it: ${trace.plan.notes.join(" ")}`
        : "I couldn't do all of it — some of what you asked for needs a provider that isn't configured.",
    );
  }

  if (trace.providerCalls.length > 0) {
    // Cost, stated the same way the workspace states it: a floor when some
    // calls reported nothing, never a zero standing in for "unknown".
    const cost =
      trace.costUsd != null
        ? `$${trace.costUsd.toFixed(4)}${trace.unpricedCalls > 0 ? " at least" : ""}`
        : "cost not reported";
    lines.push(`${trace.providerCalls.length} provider call(s), ${cost}.`);
  }

  // No trailing link line: the client renders a real anchor from `runId`, and
  // a markdown link here would show as literal brackets and parentheses in a
  // bubble that renders plain text.
  return lines.join("\n\n");
}
